name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Build
      run: rustup target add wasm32-unknown-unknown && trunk build --release
